### ISSUE TITLE
🚨🚨🚨 our project does not have a readme file.

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/ecommerce-app-cogito-bn#16]
@EvelyneUmubyeyi @kunda4 you were all supposed to use the readme.md file. You omitted it.

@kunda4 please add the necessary steps to setup Postgres in the readme.md. You checked the criteria but you did not work on it. 

@EvelyneUmubyeyi you need to add basic info about the project. Research what the readme file should contain in general. People will keep populating it. Please do this as a fix ASAP.

**Comment by EvelyneUmubyeyi** [comment]
Should I add it directly or create a PR?

**Comment by EvelyneUmubyeyi** [comment]
I ended up creating a PR

**Comment by mukunzidd** [comment]
@EvelyneUmubyeyi create a ix card on Trello, create a branch and raise a PR. That should always be the process.
